### ISSUE TITLE
ToDo: Remove Network Channel Encryption(crypto++)

### ISSUE THREAD

**Issue by nn-firc** [OpenSrceng/CSGO#3]
https://developer.valvesoftware.com/wiki/Counter-Strike:_Global_Offensive_Network_Channel_Encryption

**Comment by nn-firc** [comment]
maybe no

**Comment by nn-firc** [comment]
done

**Comment by stephen-cusi** [comment]
```python
print "hurB moment "
haha
```

**Comment by nn-firc** [comment]
> ```python
> print "hurB moment "
> haha
> ```

seems it only uses for valve server and custom servers(optional)

**Comment by nn-firc** [comment]
later
